# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapApp', '0002_auto_20171014_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_position',
            field=models.CharField(choices=[(2, 'IT'), (1, 'Faculty'), (0, 'Boss')], default='0', max_length=16),
        ),
    ]
