# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapApp', '0003_user_work_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_position',
            field=models.CharField(choices=[('0', 'Boss'), ('2', 'IT'), ('1', 'Faculty')], default='0', max_length=16),
        ),
    ]
