# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapApp', '0004_auto_20171014_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_position',
            field=models.CharField(choices=[('2', 'IT'), ('0', 'Boss'), ('1', 'Faculty')], default='0', max_length=16),
        ),
    ]
